protocols = lmtp
listen = *
log_path = /dev/stderr
info_log_path = /dev/stderr

mail_location = maildir:/home/%u/Maildir

service lmtp {
  inet_listener lmtp {
    port = 24
  }
}

passdb {
  driver = passwd
}

userdb {
  driver = passwd
}

mail_privileged_group = mail
